POST http://localhost:8080/admin/reset

###

POST  http://localhost:8080/api/users

{
  "email": "saul@bettercall.com",
  "password": "123456"
}

###

POST  http://localhost:8080/api/login

{
  "email": "saul@bettercall.com",
  "password": "123456"
}

###

POST http://localhost:8080/api/chirps
Authorization: Bearer 3e135f4e89786df298f5891712c8da4fc5e995a3e41dd364d3706b3e90214140.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIwNmRhNWU4MS1kOWFkLTQ0YTctYTYxNi0yYzE2MTk2NmU5NGIiLCJleHAiOjE3Mjk4NjI4ODgsImlhdCI6MTcyOTg1OTI4OH0.EIzck5kRcpvgUcQxi97kYubNl37Fi0DDa-7eR0ORuGI

{
  "body": "Let’s just say I know a guy... who knows a guy... who knows another guy."
}

###

POST http://localhost:8080/api/chirps
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIwNmRhNWU4MS1kOWFkLTQ0YTctYTYxNi0yYzE2MTk2NmU5NGIiLCJleHAiOjE3Mjk4NzE1OTEsImlhdCI6MTcyOTg2Nzk5MX0.hQEKziXTnIAEmIcGfwd-NzAqnxrHnqs43jp7prT5Zy4

{
  "body": "Let’s just say I know a guy... who knows a guy... who knows another guy."
}

###

POST http://localhost:8080/api/refresh
Authorization: Bearer 3e135f4e89786df298f5891712c8da4fc5e995a3e41dd364d3706b3e90214140